swagger: '2.0'
info:
  version: "1.0.0"
paths:
  /hello:
    get:
      responses:
        200:
          schema:
            $ref: "#/definitions/HelloResponse"
definitions:
  HelloResponse:
    type: object
    required:
    - hello
    properties:
      hello:
        type: string